### ISSUE TITLE
Step 3: Browser to Browser

### ISSUE THREAD

**Issue by guettli** [nuxt/nuxtjs.org#1028]
I think this needs some more words to make it easy to understand:

https://nuxtjs.org/docs/2.x/concepts/server-side-rendering

> Step 3: Browser to Browser
> 
> Navigating between pages with <NuxtLink> is done on the client side so you don't hit the server again unless you hard refresh the browser.

I stumble upon ".... so you don't hit the server again ....".

Imagine I have a CMS with 1000 pages. How should this work? Will the server side rendered page contain all these 1000 pages?

Please update the above page, since I guess other new comers will have the same question.

**Comment by pi0** [comment]
Hi @guettli. I think _hit the server again_ would be little bit misleading but in general that's true.

- For a CMS with dynamic pages, we once load dynamic page chunk for let's say `pages/blog/_id.vue` 
- During client side navigation to each dynamic page:
  - With `target: 'universal'` => We probably need to make a request to **API** server but no server-rendering happens
  - With `target: 'static'` => Since all pages are already pre-generated, only `payload.js` for each route will be loaded and rendering still happens on client-side

Hit _server_ mostly means _hit server-side-rendering_. PR welcome to reword BTW 👍

**Comment by guettli** [comment]
thank you for explaining it. Somehow this is all to complicated for me. I guess I will go a completely different way [html-over-the-wire](https://github.com/guettli/html-over-the-wire)
