### ISSUE TITLE
[OFF TOPIC] even nuxt makes some erros 

### ISSUE THREAD

**Issue by CavalcanteLeo** [nuxt/nuxtjs.org#511]
<img width="1263" alt="Captura de Tela 2020-08-13 às 13 35 13" src="https://user-images.githubusercontent.com/1735944/90161662-d7337600-dd69-11ea-9873-0eeb1c213f18.png">

**Comment by tonylangworthy** [comment]
I've also been seeing the 500 error frequently, buy I only notice it when the page is inactive for awhile. For instance, if I leave the computer, then come back to it and open the documentation, and click a link, that's when I see the 500 error.

**Comment by debs-obrien** [comment]
Thanks for the feedback. Yes I did notice that too and am wondering if it is a service worker issue. Will dig into it and see what I can find.

**Comment by tonylangworthy** [comment]
> Thanks for the feedback. Yes I did notice that too and am wondering if it is a service worker issue. Will dig into it and see what I can find.

Thank you.

**Comment by debs-obrien** [comment]
This should now be fixed. if however you come across this error again please let us know. Thanks 🙃
Ref: https://github.com/nuxt/nuxtjs.org/pull/540
https://github.com/nuxt/nuxtjs.org/pull/554
https://github.com/nuxt/nuxtjs.org/pull/567

**Comment by borisdayma** [comment]
@debs-obrien I really like to look at this repo for best practices.
I didn't understand what was the problem here.
Why did you have to make a specific page instead of just using the error layout? Also why would it fix the issue?

**Comment by debs-obrien** [comment]
It was actually a suggestion from  @Atinux I believe because we are using content for everything throughout the site and it was taking time to load the db.json as it is so big so it was using spa fallback which means we were not getting the 404 page and instead we were getting the spinner for ages and then the 404 page sometimes with 500 error. Although there seems to be 2 different problems here. One is that our 404 wasn't working at all and 2nd is that there was a 500 error on a page that actually exists. they may or may not be related but fixing the 404 issue the other issue seems to have fixed itself. Hope that helps. Why use 404 page instead of error layout? great question. I think Sebastien can answer it better than me but think it has to do with the hosting provider looking for that page.

**Comment by borisdayma** [comment]
Thank you so much @debs-obrien . This site is a great showcase so it's nice to look at how is built!
