### ISSUE TITLE
Getting a 500 error when I click on any link from the main page.

### ISSUE THREAD

**Issue by hrayr-artunyan** [nuxt/nuxtjs.org#52]
When I click on any link on the main nuxtjs.org page, I get a 500 error "Cannot read property 'status' of undefined".

**Comment by alterhu2020** [comment]
I also met this same issue ,it's interment happened ,sometimes when you go back to nuxtjs.org website in browser and click any other link in the website ,it will show the 500 issue .

By the way I also met this issue with my nuxt project in my local machine .it seems that caused by the session expired ,not sure. need someone to have a look it .

Reproduce steps could be like following:
 1. Click the nuxtjs.org webiste's hyperlink 'https://nuxtjs.org/api/configuration-loading-indicator'
 2. Not do any thing ,just leave the page opened for a few minutes.
 3. Go back the the website and click  other hyperlink like 'https://nuxtjs.org/api/pages-scrolltotop'

please let me know if you need to provide more info, your help is really appreciated .
