### ISSUE TITLE
Redirect to previous page

### ISSUE THREAD

**Issue by jarnojellesma** [nuxt/nuxtjs.org#54]
Hello,

I was wondering, how can I redirect to the previous page with e.g. the nuxt-link?

Greetings,

**Comment by alexchopin** [comment]
Hi @jarnojellesma,
According to the [vue-router](https://router.vuejs.org/en/essentials/navigation.html) documentation you can do:
`this.$router.back()`

**Comment by jossef** [comment]
suggesting to reopen. would be more elegant to use the component `nuxt-link` here with an option to go back

`<nuxt-link nuxt-link-go-back>...`

would you like me to PR this feature?

**Comment by emilpriver** [comment]
> suggesting to reopen. would be more elegant to use the component `nuxt-link` here with an option to go back
> 
> `<nuxt-link nuxt-link-go-back>...`
> 
> would you like me to PR this feature?

This would be really useful. PR if you want to :D

**Comment by manavm1990** [comment]
`<nuxt-link :to="this.$nuxt.context.from">` worked nicely 4 me.

**Comment by scscgit** [comment]
This issue seems to be getting popular, as there are not enough solutions [[1]](https://stackoverflow.com/questions/48104842/how-can-i-go-back-route-back-on-vue-router) [[2]](https://stackoverflow.com/questions/53788975/vue-router-how-to-get-previous-page-url/53789212); is there any progress, or does anyone have better better alternatives? Using `<a @click="$router.back()">go back</a>` doesn't expose the link to the user like we would expect with `n-link`. (And just as an idea, maybe this could be a good addition to a generated 404 page within Nuxt template.)

**Comment by HamadaEmpatLima** [comment]
I just use this to solve my problem `<NuxtLink to="./" ></NuxtLink >`

**Comment by scscgit** [comment]
> @HamadaEmpatLima 
> I just use this to solve my problem `<NuxtLink to="./" ></NuxtLink >`

This doesn't seem to work for me; when there's an incorrect path parameter like `a/b/123`, it seems to create a link to `a/b/` even though such a route doesn't exist. Otherwise the link is to the same page as the current one, which (due to a terrible design choice of router) doesn't do anything, as there's no way to "refresh a current page" without a hard refresh via browser, or by going back-and-forth between routes (or changing its component key).

**Comment by Ali-Nasir-01** [comment]
> I just use this to solve my problem `<NuxtLink to="./" ></NuxtLink >`

It's work for me in Nuxt error layout and It's useful =)))))

**Comment by damiothar** [comment]
I use `<a href="" @click.prevent="$router.back()">Go Back</a>`
Leave the href empty to preserve style and use `.prevent` on the click event to avoid redirection.

**Comment by damiothar** [comment]
> Using `<a @click="$router.back()">go back</a>` doesn't expose the link to the user like we would expect with `n-link`.

@scscgit You could create a component "GoBackLink"
`
<template>
  <NuxtLink :to="path"> Go Back {{ this.$route.path }}</NuxtLink>
</template>

<script>
export default {
  data() {
    return {
      path: '/',
    };
  },
  created() {
    if (this.$nuxt.context.from.path) this.path = this.$nuxt.context.from.path;
  },
};
</script>
`

**Comment by Adetutu777** [comment]
> I use `<a href="" @click.prevent="$router.back()">Go Back</a>` Leave the href empty to preserve style and use `.prevent` on the click event to avoid redirection.

This work for me. Thanks
