### ISSUE TITLE
[French] translate new guides

### ISSUE THREAD

**Issue by debs-obrien** [nuxt/nuxtjs.org#550]
French translation is almost finished under this draft pr:https://github.com/nuxt/nuxtjs.org/pull/704

**Comment by kissu** [comment]
I've created a draft PR to translate the whole 🇫🇷 guides at #704.
Do you want me to add you as a maintainer @antoineneff ? 😄 
I may ask my GF @spookyumi to review the translations later on for some advanced grammar (she was a speech therapist not so long ago).

**Comment by lihbr** [comment]
Hey @kissu if you can invite me to your fork that'd be awesome! I'll try to free up some time to help there 🙂
Happy to make some commits there if we're going one big PR for the French translation~

**Comment by kissu** [comment]
I've added you and @roiLeo on my PR. 😄 
Thanks for helping ! 🙏🏻

**Comment by kissu** [comment]
Btw folks, I want to be sure (or agree on a point of view), do you translate some of those:
- Code splitting into _fragmentation du code_
- Lifecycle into _cycle de vie_
- Server Side Rendering (SSR) into _rendu côté serveur (SSR)_

I'm asking that because as far as I know, people do not translate those but keep it in English, for future googling or even for ease of use when talking about those principles in an English place. Even myself, I do only use those terms.

And, documentations usually tend to keep those in English as far as I know (even if I do not read that much of :fr: documentation anymore 🙄).
So, do we agree to translate those specific words or keep them in English? I'd rather keep those in English. 😁

**Comment by lihbr** [comment]
That's a nice question 🤔 I tend to think that the point of a translated documentation is that it's in part addressed to people struggling with English so perhaps it's best to be as inclusive as possible by also translating those terms.

Does _Rendu Côté Serveur_ has to become _RCS_ then? _Générateur de Site Statique_ > _GSS_? 🤔

Perhaps @debs-obrien you have some "official" guidance there from the almost translated Spanish doc ☺️

**Comment by kissu** [comment]
She may take a bit of time answering because of [that](https://twitter.com/debs_obrien/status/1308870712787116032). She hopefully feels better today ! 🎉

**Comment by debs-obrien** [comment]
Hi guys, thanks. sorry yeah was not allowed a computer for a few days 😂. This is a great question and but I think it also depends on the language as something in Spanish might make sense to translate but in French doesn't. But you are right it would be great to have a kinda of guide so in future it is easy to see. However when it comes to appreviating words I don't think it should be abbreviated so SSR probably shouldn't be translated. I haven't seen that be done in Spanish docs as it doesn't really make sense. It would be like translating SPA to French. I think we have to be careful to not make things even more complicated like imagine someone searching in google for RCS and not getting a result at least if they search for SSR they will get info on what it is. Hope that helps @lihbr

**Comment by lihbr** [comment]
Thumbs up for the abbreviation thing, good luck finding something about RCS ^^'

I think we can go like that then @kissu, translating most of the tech jargon but not abbreviation.

Also sorry, been really busy recently so didn't have much time to translate docs but I saw progress on the PR!

**Comment by kissu** [comment]
Actually, not translating the abbreviations was a pretty sure thing. The main thing is to know where to draw the line of translating things. But for something like `webpackChunkName`, I admit that I rather just keep it in 🇬🇧 rather than translating it. 
For the same reason as told above: googling a very specific tech term will be a nightmare if that word was translated into some wobbly 🇫🇷 translation. 

On my side, I do translate the sentences but that kind of terms, I tend to keep them in 🇬🇧. 👌🏻

@debs-obrien glad to see you back, take care and slow down a bit. Health is important. 😀

@lihbr don't worry dude. There is still place to translate some stuff if you have some free time, no pressure. 👌🏻
@roiLeo and me are chunking the biggest part of it but having a second look (from somebody else) is always a good thing. 💪🏻 

I will give a re-read of my own translations before the merge btw.
