### ISSUE TITLE
(bug) Footer select option color

### ISSUE THREAD

**Issue by roiLeo** [nuxt/nuxtjs.org#753]
Invisible footer select option on Dark Mode

## Expected Behavior
Text color shouldn't be transparent ?

## Current Behavior
On Dark Mode, AppLangSelect component has invisible text.

## Possible Solution
Add color on select option.

## Screenshot
![screenshot](https://user-images.githubusercontent.com/9987732/93862787-e390e400-fcc2-11ea-9e90-8dbdf8058435.png)

## Context (Environment)
**OS:** Mac OS Catalina version 10.15.6 
**Browser:** Firefox Developer Edition version 81.0beta

**Comment by azrikahar** [comment]
Thanks for highlighting this issue. I think they are not "transparent" per se, but it's because Mac OS select options just happen to have very similar color with the text color (like the globe icon, "English" and arrow down icon).

I tweaked the levels of your screenshot just to confirm this is the reason for it: 
![93862787-e390e400-fcc2-11ea-9e90-8dbdf8058435 (1)](https://user-images.githubusercontent.com/42867097/93916069-8ab16200-fd3b-11ea-96cd-2e40c75fa0d0.png)

Will add a PR now :)
